language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=2.3
  matrix:
    - TAG=2.3 CACHET_VER=2.3.13 EXTRA_TAG=2

script:
  - |
    make
    make test

    if [[ "${TRAVIS_PULL_REQUEST}" == "false" && ("${TRAVIS_BRANCH}" == "master"  || -n "${TRAVIS_TAG}") ]]; then
      docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

      if [[ -n "${TRAVIS_TAG}" ]]; then
        export STABILITY_TAG="${TRAVIS_TAG}"
      fi

      if [[ -n "${EXTRA_TAG}" ]]; then
        make release TAG="${EXTRA_TAG}"
      fi

      make release

      if [[ "${TAG}" == "${LATEST_TAG}" ]]; then
        make release TAG="latest"
      fi
    fi

notifications:
  on_failure: never
  slack:
    secure: |
      sytMKHWYfSPPEPK+56nGsjoNa2qALaIRVk08kzh2ik6DEj3dQfeEdhIrK5fXLi2zT/x7DIa7XEWbYEkozSmgAQiw9R/gK8G0dEsJF3XvgazxARAVObgM2ehcW0h/Jkm7wr3NytFTp8frdBjp2EiMu9C+IvtYKkAqtvFWSK2FKIbtreJTED9Mn5SFkpLcw1V32Jl08Lsnco8gOSMk7y5hxZ5K1aRVQtEt4Vo1TT36EAO6iUiIGy1xaRGr5TEmcL+U9BeqsEM08TCejeDlEh7Oy/58JSyM4OFi5/LiA93oDrycX2XvsxbPLHfb0leEWYJ0mpWv2jNAm+SU915di6ibdg6t0qAc+5VbsXijZlbufrkVMr7k9BPTXUiZcUiBjDQSqUeEXJJyPAtuuNYfQ0AWbRH4Y+6nu6st0aRHaFo5ng7eohLGiDQpsX59Kw+xn4OyBzeISJwCFYI8auVhzOAtP09S45P47BBLuTDoIlBf0Lx3wvFNsjSVsotQLqcg0s8NusfX2vZRMNVReUtwicjAyYWY3cyCPLWww8F16g5IEpslCqRZP0a6ge+R34I36DkiURb8yuoUDndAL3A+OZi0Rd4tYccrU+DlaqAb7tpUCRO4iGcKogwA6/nVbSPH5rSKyTf9NKYmtD4Y511vqWtVKbDYOGY1vF0xGNyxMV5RaI4=