language: bash

services:
  - docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=4.10.0
    - CACHET_VER=2.3.15 TAGS=2.3,2,latest

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
