language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=2.3
  matrix:
    - TAG=2.3 CACHET_VER=2.3.13 EXTRA_TAG=2

script:
  - set -e
  - make
  - make test
  - bash "${TRAVIS_BUILD_DIR}/travis_release"
