language: bash

services:
- docker

env:
- BASE_IMAGE_STABILITY_TAG=4.11.11
- CACHET_VER=2.3.17 TAGS=2.3,2,latest

script:
- make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
