name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

env:
  BASE_IMAGE_STABILITY_TAG: 4.14.0

jobs:
  cachet-23:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: '2.4.1'
        php_ver: 7.1
        base_image_stability_tag: ${{ env.BASE_IMAGE_STABILITY_TAG }}
        tags: 2.4,2,latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
